### ISSUE TITLE
A new version is out, v32.

### ISSUE THREAD

**Issue by nepomuk16321** [Lombra/elite-api-docs#2]
Hello dear programmers,
a new version of the Journal Manual has been published in the FD Forum. 
I and probably some other CMDRs would be pleased if you would post version 32 as an online version.

https://forums.frontier.co.uk/threads/journal-docs-for-odyssey-release.575010/page-2#post-9364983

Thank you very much for your effort!

Many greetings Mathias

**Comment by Lombra** [comment]
Updated!

**Comment by nepomuk16321** [comment]
Thanks for updating. Working with the online version is just better. Thanks
