### ISSUE TITLE
Frontier has published version 34 of the "Journal".

### ISSUE THREAD

**Issue by nepomuk16321** [Lombra/elite-api-docs#3]
Hi Lombra, do you still check the Frontier ED forum sometimes ? A new version of the "Journal" has been published, version 34. Do you still have time and desire to put the new version online with "Read the docs" ? If YES, how can I help you so that you don't have to do them all by yourself ?

Many greetings nepomuk

**Comment by Lombra** [comment]
Hey,

It is on my (mental) list of things to check in every now and then, but some items tend to fall off that list every now and then! Have not checked it for a while, so I hadn't yet seen this. I will certainly take a look.

The process is fairly straightforward and mostly automated. The main thing that would help is if Frontier would distribute the source documents in a format better suited for parsing. :)
